service: Button2slack

frameworkVersion: ">=1.71.1 <2.0.0"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  timeout: 60
  memorySize: 128

package:
  individually: true
  include:
    - handlers/*
  exclude:
    - .git/**
    - venv/**
    - tmp.*
    - _tmp*
    - .envrc*
    - deploy.sh
    - .python-version
    - .git*
    - jira*
    - empty_event.json
    - README.md

plugins:
  - serverless-python-requirements

custom:
  # serverless-python-requirements
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  main:
    handler: src/handler.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    environment:
      SLACK_NOTIFICATION_URL: ${env:SLACK_NOTIFICATION_URL}
      MESSAGE: ${env:MESSAGE}

resources:
  Resources:
    IoT1ClickButton:
      Type: "AWS::IoT1Click::Device"
      Properties:
        DeviceId: ${env:IoT1CLICK_DEVICE_ID}
        Enabled: "true"

# なぜかエラーになるため以下は手作業で構築
#    BasicProject:
#      Type: "AWS::IoT1Click::Project"
#      Properties:
#        ProjectName: "project-with-placements"
#        Description: "description"
#        PlacementTemplate:
#          DeviceTemplates:
#            DefaultTemplate:
#              DeviceType: "button"
#              CallbackOverrides:
#                onClickCallback:
#                  Fn::GetAtt: [ "StopStartLambdaFunction", "Arn" ]
#    BasicPlacement:
#      Type: "AWS::IoT1Click::Placement"
#      Properties:
#        ProjectName: !Ref BasicProject
#        PlacementName: "Button2slack-placement"